### ISSUE TITLE
Can't create a superuser

### ISSUE THREAD

**Issue by nadiasvertex** [nuodb/nuodb-django#2]
When I enable the DJango admin on django 1.5.5, I cannot create a super user and the admin site fails to work:

cnelson@hpvm:/media/cnelson/meps/projects/ma/common/translation_tool/site  (master)$ python manage.py createsuperuser
DatabaseError: 

$ python -V
Python 2.7.5+
$ uname -a
Linux hpvm 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tvincentNuoDB** [comment]
Hi,

My apologizes that there was no response to this issue. I've done some testing and can create a superuser with the adapter in both Django 1.5 and 1.6. It seems like this issue may have been resolved in the interim, please don't hesitate to reopen this issue if the problem persists.
